version: '3'
services:
  reactjs:
    command: npm start
    restart: unless-stopped
    container_name: reactjs
    image: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/home/node/app/src:ro